name = 'theme'
license = 'MIT'
licenselink = 'https://github.com/jakobvase/hugo-blog/theme/LICENSE'
description = 'Theme description'

# The home page of the theme, where the source can be found
homepage = 'https://github.com/jakobvase/hugo-blog/theme'

# If the theme has a single author
[author]
  name = 'Jakob Vase'
  homepage = 'https://vase.dev'
